### ISSUE TITLE
Changing Modified Date of Filename according to suffix. System.ArgumentOutOfRangeException: Not a valid Win32 FileTime.

### ISSUE THREAD

**Issue by iohn2000** [iohn2000/fixdate#2]
C:\Users\fleckj\OneDrive\ScannedDocs>fixDate.exe
Changing Modified Date of Filename according to suffix.
System.ArgumentOutOfRangeException: Not a valid Win32 FileTime.
   at System.DateTime.ToFileTimeLeapSecondsAware(Int64 ticks)
   at System.DateTime.ToFileTimeUtc()
   at System.IO.FileSystem.SetLastWriteTime(String fullPath, DateTimeOffset time, Boolean asDirectory)
   at System.IO.FileSystemInfo.set_LastWriteTimeCore(DateTimeOffset value)
   at System.IO.FileSystemInfo.set_LastWriteTime(DateTime value)
   at fixDate.FixDates.CheckFileDateAndFix(Boolean forceUpdate, String f, SortedList`2 dateFormats, SortedList`2 parseFormats, List`1 theReport) in C:\Users\fleckj\OneDrive\dev\fixDate\fixDate\FixDates.cs:line 56
   at fixDate.FixDates.LosGehts(Boolean forceUpdate, String relativeStartPath) in C:\Users\fleckj\OneDrive\dev\fixDate\fixDate\FixDates.cs:line 35
   at fixDate.Executor.Execute(Boolean forceUpdate, String relStartPath) in C:\Users\fleckj\OneDrive\dev\fixDate\fixDate\Executor.cs:line 26
   at haha.Program.Main(Boolean f, String p) in C:\Users\fleckj\OneDrive\dev\fixDate\fixDate\Program.cs:line 28

C:\Users\fleckj\OneDrive\ScannedDocs>

**Comment by iohn2000** [comment]
- combination of onedrive and cryptomator breaks things, .net library cannot access/modify files

**Comment by iohn2000** [comment]
- one possible solution is to use operations from powershell, console directly.
- see branch [bugfix-1-onedrive](https://github.com/iohn2000/fixdate/tree/bugfix-1-onedrive)

In Powershell, this works:
```(gci)[1].LastWriteTimeUtc = (New-Object datetime 2013,12,31)```
[Link](https://stackoverflow.com/a/62372699/925)

start powershell from dos console:
```powershell -command "(Get-Item 'C:\path\to\your\file.txt').LastWriteTime=('09/01/2024 12:34')"```

**Comment by iohn2000** [comment]
with this commit:
[https://github.com/iohn2000/fixdate/commit/c3ce60c9d170e19006655ef7e1473dfcf49fe659](https://github.com/iohn2000/fixdate/commit/c3ce60c9d170e19006655ef7e1473dfcf49fe659)
onedrive + cryptomator **is working** but still very slow
